# Generated by Django 4.1.4 on 2022-12-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bform",
            fields=[
                (
                    "form_pk",
                    models.CharField(
                        max_length=100000000, primary_key=True, serialize=False
                    ),
                ),
                ("lineuid", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=20)),
                ("nickname", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
    ]
